language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
after_success:
  - git config --global user.email "travis-ci@localhost"
  - git config --global user.name "Travis-CI"
  - npm run --silent deploy -- --silent --repo https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git --tag build.$TRAVIS_BUILD_NUMBER
